name: Build Kernel SM-T285

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout mã nguồn Kernel
        run: |
          git clone https://github.com/maitatthanh9/Build_Kernel_SM-T285.git kernel_source
          cd kernel_source
          git checkout main

      - name: Cài đặt công cụ build
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential curl flex gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi git libncurses-dev python3 unzip zlib1g-dev

      - name: Build Kernel
        run: |
          cd kernel_source
          export ARCH=arm
          export CROSS_COMPILE=arm-linux-gnueabi-
          make gtexswifi_defconfig
          make -j$(nproc)
